services:
  backend-flask:
    build: ./web-server      
    container_name: webserver-iot
    ports: 
      - "5000:5000"
    networks:
      - network-iot
    environment:
      - INFLUX_HOST=${INFLUX_HOST}
      - INFLUX_TOKEN=${INFLUX_TOKEN}
      - INFLUX_DB=${INFLUX_DB}
      - PYTHONNUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
    depends_on:
      - db-influxdb
  
  db-influxdb:
    container_name: influxdb-core
    image: influxdb:3-core
    ports:
      - "8181:8181"
    command:
      - influxdb3
      - serve
      - --node-id=node0
      - --object-store=file  #type of object store to use. file: local file system
      - --data-dir=/var/lib/influxdb3/data #store the data in the container
      - --plugin-dir=/var/lib/influxdb3/plugins #search plugins in the container   
    environment:
      - INFLUXDB3_START_WITHOUT_AUTH=true
    volumes:
      - type: bind
        source: C:/Users/jhorv/Documents/test/test-influxdb/data
        target: /var/lib/influxdb3/data
      - type: bind
        source: C:/Users/jhorv/Documents/test/test-influxdb/plugins
        target: /var/lib/influxdb3/plugins
    networks:
      - network-iot

  frontend-grafana:
    container_name: grafana-iot
    image: grafana/grafana-enterprise
    ports:
      - '3000:3000'  
    networks:
      - network-iot
    depends_on:
      - db-influxdb

networks:
  network-iot:
    name: network-iot #the name for change the default name
    driver: bridge
